---
- name: Install and configure Nginx
  hosts: all
  become: yes
  vars:
    nginx_port: 80
    root_dir: /usr/share/nginx/html
  
  tasks:
    - name: Install Nginx
      package:
        name: nginx
        state: present
      notify: restart nginx

    - name: Create HTML file from template
      template:
        src: files/index.html
        dest: "{{ root_dir }}/index.html"
        owner: root
        group: root
        mode: '0644'
      notify: restart nginx

    - name: Copy Nginx configuration file
      template:  # Используем template вместо copy для nginx.conf тоже
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'
      notify: restart nginx

    - name: Ensure Nginx is running and enabled
      service:
        name: nginx
        state: started
        enabled: yes

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted